### ISSUE TITLE
Does not work on 30.0

### ISSUE THREAD

**Issue by rahaaatul** [eebssk1/SRBeep2#3]
I've put the `SRBeep.dll` file in `C:\Program Files\obs-studio\obs-plugins\64bit` and it's doing nothing, there's no sound.

I'm using the latest `30.0.0` stable OBS build.

**Comment by eebssk1** [comment]
Have you put the audio files?
Check the first release(zip file) for full content.
Dll release are just updates.

**Comment by rahaaatul** [comment]
Oh, I've put those audio files from where you forked it from. Let me try yours.
