### ISSUE TITLE
Legacy build.

### ISSUE THREAD

**Issue by Supded** [eebssk1/SRBeep2#4]
Can you build new release for generic architecture? Thanks.

**Comment by eebssk1** [comment]
> Can you build new release for generic architecture? Thanks.

Hi. Please check version 2.2.0 https://github.com/eebssk1/SRBeep2/releases/tag/v2.2.0

**Comment by Supded** [comment]
Thanks, but i have no sse 4.2 instructions.

**Comment by eebssk1** [comment]
> Thanks, but i have no sse 4.2 instructions.

Hmm. This seems a bit hard to achieve becase SDL seems depend on it.

**Comment by eebssk1** [comment]
> Thanks, but i have no sse 4.2 instructions.

Can you test if this version works for you?

https://github.com/eebssk1/SRBeep2/releases/tag/v2.2.0-core2
