### ISSUE TITLE
not getting any audio. (was on older version of obs 27.01 and just updated just for this)

### ISSUE THREAD

**Issue by amnes7y** [eebssk1/SRBeep2#5]
files are exactly where should be but I'm not able to get it to work like I could with previous version.

currently on 30.1.2

![image_2024-04-11_135535881](https://github.com/eebssk1/SRBeep2/assets/67816105/8dd2baa2-8d1b-482c-818a-a30d9e0c29c3)
![Screenshot 2024-04-11 135621](https://github.com/eebssk1/SRBeep2/assets/67816105/c95d4a54-b516-42d2-939d-a6c451e3593f)

**Comment by amnes7y** [comment]
also tried without SRBeep.dll if that's what it was but still nothing

**Comment by eebssk1** [comment]
Pls provide OBS logs

**Comment by eebssk1** [comment]
The data directory must be changed to SRBeep2 as well. They always equal to the module name.

**Comment by amnes7y** [comment]
changing the folder name to SRBeep2 was it and now I have sounds playing for everything, did not think about that at all lol thank you for replying.
